"""Core package for the text adventure framework."""

from .analytics import (
    AdventureComplexityMetrics,
    AdventureContentDistribution,
    AdventureReachabilityReport,
    ItemConsumption,
    ItemFlowDetails,
    ItemFlowReport,
    ItemRequirement,
    ItemSource,
    TextDistributionSummary,
    analyse_item_flow,
    analyse_item_flow_from_definitions,
    analyse_item_flow_from_file,
    compute_adventure_complexity,
    compute_adventure_complexity_from_definitions,
    compute_adventure_complexity_from_file,
    compute_adventure_content_distribution,
    compute_adventure_content_distribution_from_definitions,
    compute_adventure_content_distribution_from_file,
    compute_scene_reachability,
    compute_scene_reachability_from_definitions,
    compute_scene_reachability_from_file,
    format_item_flow_report,
    format_complexity_report,
    format_content_distribution_report,
    format_reachability_report,
)
from .llm import LLMClient, LLMClientError, LLMMessage, LLMResponse, iter_contents
from .llm_providers import (
    AnthropicMessagesClient,
    CohereChatClient,
    OpenAIChatClient,
    register_builtin_providers,
)
from .llm_provider_registry import LLMProviderRegistry, parse_cli_options
from .story_engine import StoryChoice, StoryEngine, StoryEvent
from .scripted_story_engine import (
    ScriptedStoryEngine,
    load_scenes_from_file,
    load_scenes_from_mapping,
)
from .markdown import render_markdown
from .multi_agent import (
    Agent,
    AgentTrigger,
    AgentTurnResult,
    CoordinatorDebugState,
    MultiAgentCoordinator,
    QueuedAgentMessage,
    ScriptedStoryAgent,
)
from .llm_story_agent import LLMStoryAgent
from .persistence import (
    FileSessionStore,
    InMemorySessionStore,
    SessionSnapshot,
    SessionStore,
)
from .memory import MemoryEntry, MemoryLog, MemoryRequest
from .tools import KnowledgeBaseTool, Tool, ToolResponse
from .world_state import WorldState

__all__ = [
    "WorldState",
    "StoryChoice",
    "StoryEvent",
    "StoryEngine",
    "AdventureComplexityMetrics",
    "AdventureContentDistribution",
    "AdventureReachabilityReport",
    "ItemConsumption",
    "ItemFlowDetails",
    "ItemFlowReport",
    "ItemRequirement",
    "ItemSource",
    "TextDistributionSummary",
    "analyse_item_flow",
    "analyse_item_flow_from_definitions",
    "analyse_item_flow_from_file",
    "compute_adventure_complexity",
    "compute_adventure_complexity_from_definitions",
    "compute_adventure_complexity_from_file",
    "compute_adventure_content_distribution",
    "compute_adventure_content_distribution_from_definitions",
    "compute_adventure_content_distribution_from_file",
    "compute_scene_reachability",
    "compute_scene_reachability_from_definitions",
    "compute_scene_reachability_from_file",
    "format_item_flow_report",
    "format_complexity_report",
    "format_content_distribution_report",
    "format_reachability_report",
    "ScriptedStoryEngine",
    "load_scenes_from_file",
    "load_scenes_from_mapping",
    "Agent",
    "AgentTrigger",
    "AgentTurnResult",
    "ScriptedStoryAgent",
    "MultiAgentCoordinator",
    "CoordinatorDebugState",
    "QueuedAgentMessage",
    "LLMStoryAgent",
    "render_markdown",
    "Tool",
    "ToolResponse",
    "KnowledgeBaseTool",
    "MemoryEntry",
    "MemoryLog",
    "MemoryRequest",
    "LLMClient",
    "LLMClientError",
    "LLMMessage",
    "LLMResponse",
    "AnthropicMessagesClient",
    "CohereChatClient",
    "OpenAIChatClient",
    "register_builtin_providers",
    "LLMProviderRegistry",
    "parse_cli_options",
    "iter_contents",
    "SessionSnapshot",
    "SessionStore",
    "InMemorySessionStore",
    "FileSessionStore",
]
