name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build:
    name: Tests and Checks (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Ruff
        run: ruff check src tests

      - name: Check formatting with Black
        run: black --check src tests

      - name: Run mypy
        run: mypy src

      - name: Run tests
        run: pytest -q
