name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build:
    name: Tests and Checks (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Cache lychee binary
        id: cache-lychee
        uses: actions/cache@v4
        with:
          path: ~/.local/bin/lychee
          key: lychee-v0.20.1

      - name: Install lychee
        if: steps.cache-lychee.outputs.cache-hit != 'true'
        run: |
          curl -sSfL -o lychee.tar.gz https://github.com/lycheeverse/lychee/releases/download/lychee-v0.20.1/lychee-x86_64-unknown-linux-gnu.tar.gz
          tar -xzf lychee.tar.gz
          mkdir -p ~/.local/bin
          mv lychee ~/.local/bin/lychee
        shell: bash

      - name: Add local bin to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Run Ruff
        run: ruff check src tests

      - name: Check formatting with Black
        run: black --check src tests

      - name: Run mypy
        run: mypy src

      - name: Validate documentation guardrails
        run: |
          python -m scripts.check_agents_guidance --diff-only
          codespell --toml docs/codespell.toml docs web README.md
          lychee --config docs/lychee.toml docs web README.md

      - name: Run tests
        run: pytest -q
