name: Container Deployment

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      push_image:
        description: 'Push the built image to GitHub Container Registry'
        required: true
        default: 'false'
        type: choice
        options:
          - 'false'
          - 'true'

jobs:
  build-image:
    name: Build container image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
      PUSH_IMAGE: ${{ github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && github.event.inputs.push_image == 'true') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=tag
            type=sha
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/tags/v') }}

      - name: Log in to GitHub Container Registry
        if: env.PUSH_IMAGE == 'true'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and (optionally) push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: ${{ env.PUSH_IMAGE == 'true' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Summarize image build
        shell: bash
        run: |
          {
            echo "## Image build summary"
            echo "- Registry: ${REGISTRY}"
            echo "- Repository: ${IMAGE_NAME}"
            echo "- Pushed: ${PUSH_IMAGE}"
            echo "- Tags:"
            while IFS= read -r tag; do
              if [[ -n "${tag}" ]]; then
                echo "  - ${tag}"
              fi
            done <<< "${{ steps.meta.outputs.tags }}"
          } >> "${GITHUB_STEP_SUMMARY}"
